MaintenanceSchedule.Web/Areas/Admin/Controllers/ServiceController.cs
using RTE;
using System;
using System.IO;
using System.Web;
using System.Linq;
using Vendare.Error;
using System.Web.Mvc;
using System.Drawing;
using System.Web.UI.WebControls;
using System.Collections.Specialized;
//using MaintenanceSchedule.Web.Filters;
using MaintenanceSchedule.Library.Utilities;
using MaintenanceSchedule.Web.Areas.Admin.Models;
using MaintenanceSchedule.Core.Common.Configuration;
using MaintenanceSchedule.Core.Queries.Datlichbaoduong;
using MaintenanceSchedule.Core.Commands.Datlichbaoduong;
using ServiceEntity = MaintenanceSchedule.Entity.Datlichbaoduong.Service;
using System.Collections.Generic;

namespace MaintenanceSchedule.Web.Areas.Admin.Controllers
{
    //[Authentication]
    public class ServiceController : AdminController
    {
        private readonly IDeleteServiceCommand _deleteServiceCommand;
        private readonly ICreateServiceCommand _createServiceCommand;
        private readonly IUpdateServiceCommand _updateServiceCommand;
        private readonly IUpdateServiceImageCommand _updateServiceImageCommand;

        private readonly IServiceQuery _serviceQuery;
        private readonly IGetServiceListPagingQuery _getServiceListPagingQuery;

        public ServiceController(IUpdateServiceImageCommand updateServiceImageCommand, IDeleteServiceCommand deleteServiceCommand,
                                 ICreateServiceCommand createServiceCommand, IUpdateServiceCommand updateServiceCommand,
                                 IServiceQuery serviceQuery, IGetServiceListPagingQuery getServiceListPagingQuery)
        {
            _createServiceCommand = createServiceCommand;
            _updateServiceCommand = updateServiceCommand;
            _deleteServiceCommand = deleteServiceCommand;
            _updateServiceImageCommand = updateServiceImageCommand;

            _serviceQuery = serviceQuery;
            _getServiceListPagingQuery = getServiceListPagingQuery;
        }

        //[Authorize]
        public ActionResult ServicePage(SearchPageForm searchPageForm)
        {
            try
            {
                return base.Page<GetServiceListPagingRequest, GetServiceListPagingResponse, ServiceViewModel, ServiceEntity>(searchPageForm, _getServiceListPagingQuery, TransformToViewModel);
            }
            catch (Exception ex)
            {
                var detail = new NameValueCollection();
                if (ex.InnerException != null) detail.Add("innerExeption", ex.InnerException.Message);
                new LoggableException(ex, detail);
                return JsonErrorResult(ex.ToString());
            }
        }

        //[Authorize]
        public ActionResult Index()
        {
            ShowDescribesPage(DescribeType.List, Describe.ServiceLabel);
            return View(new ServiceFormModel());
        }

        //[Authorize]
        public ActionResult Create()
        {
            ShowDescribesPage(DescribeType.Create, Describe.ServiceLabel);
            var formModel = new ServiceFormModel
            {
                Content = PrepairEditor("Content", delegate (Editor editor)
                {
                    editor.Width = Unit.Percentage(100);
                    editor.Height = Unit.Pixel(700);
                    if (Request.HttpMethod == "POST")
                        editor.UploadImage += new UploadImageEventHandler(Editor_UploadImage);
                }).Text
            };
            return View(formModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ServiceFormModel model, HttpPostedFileBase[] files)
        {
            int serviceId = 0;
            model.Content = PrepairEditor("Content", delegate (Editor editor) { }, model.Content).Text;

            var response = _createServiceCommand.Invoke(new CreateServiceRequest
            {
                ServiceId = model.Id,
                ServiceTags = model.Tags,
                ServiceTitle = model.Title,
                ServiceImage = model.Image,
                ServiceContent = model.Content,
                ServiceDescrtiption = model.Description
            });

            if (response.Status == CreateServiceStatus.Success)
            {
                serviceId = response.ServiceId;

                if (files != null && files.Length > 0 && files[0] != null)
                {
                    var file = files[0];
                    var extension = Path.GetExtension(file.FileName);
                    model.Image = string.Concat(new string[]
                    {
                        string.Join(Constant.COLON_SYMBOL_DASH.ToString(),
                        new string[]
                        {
                            serviceId.ToString(),
                            Characters.ConvertToUnSign3(model.Title)
                        }),
                        extension
                    });

                    if (!string.IsNullOrEmpty(model.Image))
                    {
                        var responseImage = _updateServiceImageCommand.Invoke(new UpdateServiceImageRequest
                        {
                            ServiceId = serviceId,
                            ServiceImage = model.Image
                        });

                        if (responseImage.Status)
                            SaveImages(file, model.Image);
                        else
                            ModelState.AddModelError("SaveImage", "Cập nhật hình lỗi");
                    }
                }
            }
            else
            {
                ModelState.AddModelError("InsertData", "Tạo dịch vụ lỗi. Liên hệ admin.");
            }

            var errors = ModelState.Values.SelectMany(value => value.Errors).ToList();
            if (errors.Count <= 0)
                ViewBag.Message = "Tạo dịch vụ thành công!";
            
            ShowDescribesPage(DescribeType.Edit, Describe.ServiceLabel);
            return View(model);
        }

        //[Authorize]
        public ActionResult Edit(int id)
        {
            var formModel = new ServiceFormModel();
            var service = _serviceQuery.GetService(id);
            if (service != null)
            {
                formModel = new ServiceFormModel
                {
                    Id = service.Id,
                    Tags = service.Tags,
                    Title = service.Title,
                    Image = service.Image,
                    Description = service.Description,
                    Content = PrepairEditor("Content", delegate (Editor editor)
                    {
                        editor.Width = Unit.Percentage(100);
                        editor.Height = Unit.Pixel(700);
                        if (Request.HttpMethod == "POST")
                            editor.UploadImage += new UploadImageEventHandler(Editor_UploadImage);
                    }, service.Content).Text
                };
            }
            return View(formModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ServiceFormModel model, HttpPostedFileBase[] files)
        {
            var serviceId = model.Id;
            HttpPostedFileBase file = null;

            if (files != null && files.Length > 0 && files[0] != null)
            {
                file = files[0];
                var extension = Path.GetExtension(file.FileName);
                model.Image = string.Concat(new string[]
                {
                        string.Join(Constant.COLON_SYMBOL_DASH.ToString(),
                        new string[]
                        {
                            serviceId.ToString(),
                            Characters.ConvertToUnSign3(model.Title)
                        }),
                        extension
                });
            }

            model.Content = PrepairEditor("Content", delegate (Editor editor) { }, model.Content).Text;

            var response = _updateServiceCommand.Invoke(new UpdateServiceRequest
            {
                ServiceId = serviceId,
                ServiceTags = model.Tags,
                ServiceTitle = model.Title,
                ServiceImage = model.Image,
                ServiceContent = model.Content,
                ServiceDescription = model.Description
            });

            if (response.Status == UpdateServiceStatus.Success)
            {
                try
                {
                    if (!string.IsNullOrEmpty(model.Image))
                        SaveImages(file, model.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("SaveImage", ex.Message.ToString());
                }
            }
            else
            {
                ModelState.AddModelError("SaveData", "Cập nhật dịch vụ lỗi. Liên hệ admin.");
            }

            var errors = ModelState.Values.SelectMany(value => value.Errors).ToList();
            if (errors.Count <= 0)
                ViewBag.Message = "Cập nhật dịch vụ thành công!";
            
            ShowDescribesPage(DescribeType.Edit, Describe.ServiceLabel);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var response = _deleteServiceCommand.Invoke(new DeleteServiceRequest { ServiceId = id });
            if (response.Status)
            {
                //Delete images on disk
                var realImageFile = !string.IsNullOrEmpty(response.Image) ? Server.MapPath(ConfigVariable.RelativeServiceUrl + response.Image) : string.Empty;
                var mediumImageFile = !string.IsNullOrEmpty(response.Image) ? Server.MapPath(ConfigVariable.RelativeServiceMediumUrl + response.Image) : string.Empty;
                var thumbImageFile = !string.IsNullOrEmpty(response.Image) ? Server.MapPath(ConfigVariable.RelativeServiceThumbUrl + response.Image) : string.Empty;

                if (Directory.Exists(realImageFile))

MaintenanceSchedule.Web/Areas/Service/Controllers/ServiceController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Collections.Generic;
using yellowx.Framework.Data.Paging;
using FrameStore.Core.Mvc.Extensions;
using MaintenanceSchedule.Web.Controllers;
using MaintenanceSchedule.Library.Utilities;
using MaintenanceSchedule.Core.Queries.Vienauto;
using MaintenanceSchedule.Web.Areas.Common.Models;
using MaintenanceSchedule.Web.Areas.Service.Models;
using MaintenanceSchedule.Core.Common.Configuration;
using MaintenanceSchedule.Core.Queries.Datlichbaoduong;

namespace MaintenanceSchedule.Web.Areas.Service.Controllers
{
    public class ServiceController : BaseController
    {
        private readonly IServiceQuery _serviceQuery;
        private readonly IGetYearListQuery _getYear;
        private readonly IGetModelListQuery _getModel;
        private readonly IGetAllManufacturerListQuery _allManufactureQuery;        
        
        public ServiceController(IServiceQuery serviceQuery, IGetAllManufacturerListQuery allManufactureQuery,
                                 IGetModelListQuery getModel, IGetYearListQuery getYear)
        {
            _serviceQuery = serviceQuery;
            _allManufactureQuery = allManufactureQuery;
            _getModel = getModel;
            _getYear = getYear;
        }

        public ActionResult View(int id, string title)
        {
            var service = _serviceQuery.GetService(id);
            ViewBag.ServiceId = id.ToString();
            BuildSEO(SEOType.ServiceDetail, service.Title, id.ToString());
            var viewModel = LoadViewModel();
            return View(viewModel);
        }

        public ActionResult Detail(int id)
        {
            var service = _serviceQuery.GetService(id);
            //BuildSEO(SEOType.ServiceDetail, service.Title, id.ToString());

            var nextService = _serviceQuery.GetNextService(id);
            var lastService = _serviceQuery.GetLastService(id);

            if (service != null)
            {
                return PartialView("~/Areas/Service/Views/Service/_Detail.cshtml", new ServiceViewModel
                {
                    Id = service.Id,
                    Tags = service.Tags,
                    Title = service.Title,
                    Image = service.Image,
                    Content = service.Content,
                    EntryDate = service.EntryDate,
                    Description = service.Description,
                    ListLatestServices = _serviceQuery.GetLatestService(),
                    NextService = nextService != null ? nextService.Id : 0,
                    PreviousService = lastService != null ? lastService.Id : 0
                });
            }
            return PartialView("~/Areas/Service/Views/Service/_Detail.cshtml", new ServiceViewModel());
        }

        public ActionResult Index()
        {
            BuildSEO(SEOType.Index);
            var viewModel = (HomeViewModel)TempData["HomeViewModel"];
            viewModel = LoadViewModel(viewModel);
            return View(viewModel);
        }

        public ActionResult List()
        {
            return PartialView("~/Areas/Service/Views/Service/_Index.cshtml");
        }

        [HttpPost]
        public ActionResult Index(HomeViewModel viewModel)
        {
            var viewModelReturn = new HomeViewModel();
            viewModelReturn.Message = string.Empty;

            try
            {
                var mailContentDictionary = new Dictionary<string, string>
                {
                    { "MANUFACTURER", viewModel.ManufacturerName },
                    { "MODEL", viewModel.ModelName },
                    { "YEAR", viewModel.YearName },
                    { "CONTENT", viewModel.Content },
                    { "CUSTOMERNAME", viewModel.CustomerName },
                    { "CUSTOMERPHONE", viewModel.CustomerPhone }
                };
                Mail.Send(ConfigVariable.MailFrom, ConfigVariable.MailTo, new string[] { }, mailContentDictionary, "Đặt lịch bảo dưỡng");
                viewModelReturn.Message = "Chúc mừng bạn đã đặt lịch bảo dưỡng thành công, chúng tôi sẽ ưu tiên xe của bạn!";
            }
            catch (Exception ex)
            {
                viewModelReturn.Message = ex.ToString();
            }

            LoadViewModel(viewModelReturn);
            TempData["HomeViewModel"] = viewModelReturn;

            return RedirectToRoute("Default");
        }

        private PagingResult<MaintenanceSchedule.Entity.Datlichbaoduong.Service> getListService(Paging paging)
        {
            return _serviceQuery.GetServices(paging);
        }

        public ActionResult GetServices(int index, int size)
        {
            PagingResult<MaintenanceSchedule.Entity.Datlichbaoduong.Service> result;

            var paging = new Paging { Index = index, Size = size };            
            result = _serviceQuery.GetServices(paging);

            var totalPages = Convert.ToInt32(Math.Ceiling(result.TotalCount * 1.0 / size));

            var pages = new List<Pages>();
            for (var i = 1; i <= totalPages; i++)
                pages.Add(new Pages { Page = i });

            return JsonSuccessResult(new
            {
                pages = pages,
                currentIndex = index,
                items = result.Items.Select(x =>
                new ServiceViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    Image = x.Image,
                    Content = x.Content,
                    Description = !string.IsNullOrEmpty(x.Description) ? Characters.Chop(x.Description, 100) : string.Empty
                }).ToList(),
            });
        }

        public ActionResult LoadModelByManufacturer(string manufacturerId)
        {
            var response = _getModel.Invoke(new GetModelListQueryRequest { ManufacturerId = int.Parse(manufacturerId) }).Items.OrderBy(m => m.Name);
            return JsonSuccessResult(response);
        }

        public ActionResult LoadYearByModel(string modelId)
        {
            var response = _getYear.Invoke(new GetYearListQueryRequest { ModelId = int.Parse(modelId) }).Items.OrderBy(y => y.Name);
            return JsonSuccessResult(response);
        }

        private HomeViewModel LoadViewModel(HomeViewModel viewModel = null)
        {
            if (viewModel == null)
                viewModel = new HomeViewModel();

            var manufacturers = _allManufactureQuery.Invoke(new GetAllManufacturerListQueryRequest()).Items;

            var listViewManufacturers = manufacturers.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Name }).ToList();
            listViewManufacturers.Insert(0, new SelectListItem { Text = "Chọn hãng xe", Value = "0" });

            var logoStrings = new string[] { "Toyota", "Hyundai", "Mazda", "Nissan", "Kia", "Acura", "Lexus", "BMW",
                                             "Fiat", "Ford", "Chrysler", "Chevrolet", "Honda", "Cadillac", "Volkswagen" };

            viewModel.ManufacturerId = viewModel.ManufacturerId != 0 ? viewModel.ManufacturerId : 0;
            viewModel.Manufacturers = listViewManufacturers;
            viewModel.Logos = manufacturers.Where(x => logoStrings.Contains(x.Name))
                                           .OrderBy(x => x.Name)
                                           .Select(x => new LogoViewModel { Alt = x.Name, Path = x.Logo }).ToList();
            return viewModel;
        }
    }
}

MaintenanceSchedule.Web/Areas/Admin/Views/Service/Create.cshtml
@model MaintenanceSchedule.Web.Areas.Admin.Models.ServiceFormModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="createServiceModal" class="form-container">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-success" role="alert" style="width: 50%;">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <b>@ViewBag.Message</b>
        </div>
    }
    @if (!MvcHtmlString.IsNullOrEmpty(Html.ValidationSummary()))
    {
        @Html.ValidationSummary()
    }

    @using (Html.BeginForm("Create", "Service", FormMethod.Post, new
    {
        id = "createServiceForm",
        area = "Admin",
        @class = "form-service form-horizontal",
        enctype = "multipart/form-data"
    }))
    {
        @Html.HiddenFor(m => m.Id)
        <div class="col-md-9 col-sm-10 col-xs-9">
            <div class="form-group">
                <b>Tiêu đề</b>
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Title, new { placeholder = "Tiêu đề", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Mô tả ngắn</b>
            </div>
            <div class="form-group">
                @Html.TextAreaFor(m => m.Description, new { placeholder = "Mô tả ngắn", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Nội dung</b>
            </div>
            <div class="form-group">
                @Html.Raw(ViewBag.Editor)
            </div>
            <div class="form-group">
                <b>Tags</b>
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Tags, new { placeholder = "Tags", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Chọn hình ảnh đại diện</b>
            </div>
            <div class="form-group">
                <input type="file" name="files" value="" multiple="multiple" />
            </div>
            <div class="form-group">
                <img src="@Model.DisplayImage" />
            </div>
            <div class="form-group" style="float: right;">
                <button type="submit" id="btnCreate" class="btn btn-primary" data-normal-text="Cập nhật">Cập nhật</button>
                <button type="button" class="btn btn-default" onclick="window.location.href='/Admin/Service/Index'">Trở về</button>
            </div>
        </div>
    }
</div>

MaintenanceSchedule.Web/Areas/Admin/Views/Service/Edit.cshtml
@model MaintenanceSchedule.Web.Areas.Admin.Models.ServiceFormModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="editServiceModal" class="form-container">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-success" role="alert" style="width: 50%;">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <b>@ViewBag.Message</b>
        </div>
    }
    @if (!MvcHtmlString.IsNullOrEmpty(Html.ValidationSummary()))
    {
        @Html.ValidationSummary()
    }

    @using (Html.BeginForm("Edit", "Service", FormMethod.Post, new
    {
        id = "editServiceForm",
        area = "Admin",
        @class = "form-service form-horizontal",
        enctype = "multipart/form-data"
    }))
    {
        @Html.HiddenFor(m => m.Id)
        <div class="col-md-9 col-sm-10 col-xs-9">
            <div class="form-group">
                <b>Tiêu đề</b>
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Title, new { placeholder = "Tiêu đề", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Mô tả ngắn</b>
            </div>
            <div class="form-group">
                @Html.TextAreaFor(m => m.Description, new { placeholder = "Mô tả ngắn", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Nội dung</b>
            </div>
            <div class="form-group">
                @Html.Raw(ViewBag.Editor)
            </div>
            <div class="form-group">
                <b>Tags</b>
            </div>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Tags, new { placeholder = "Tags", @class = "form-control" })
            </div>
            <div class="form-group">
                <b>Chọn hình ảnh đại diện</b>
            </div>
            <div class="form-group">
                <input type="file" name="files" value="" multiple="multiple" />
            </div>
            <div class="form-group">
                <img src="@Model.DisplayImage" />
            </div>
            <div class="form-group" style="float: right;">
                <button type="submit" id="btnEdit" class="btn btn-primary" data-normal-text="Cập nhật">Cập nhật</button>
                <button type="button" class="btn btn-default" onclick="window.location.href='/Admin/Service/Index'">Trở về</button>
            </div>
        </div>
    }
</div>

MaintenanceSchedule.Web/Areas/Admin/Views/Service/Index.cshtml
@model MaintenanceSchedule.Web.Areas.Admin.Models.ServiceFormModel
@{
    ViewBag.Title = "Dịch vụ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="panel panel-">
    <div class="panel-heading" primary style="float: right; margin-bottom: 20px;">
        <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Create")'">Tạo mới</button>
    </div>
    <div class="panel-body">
        <table id="grid-service" data-url="@Url.Action("ServicePage")"
               data-edit-url="@Url.Action("Edit")"
               data-delete-message="Bạn có muốn xóa dịch vụ này không?"
               data-delete-url="@Url.Action("Delete")" class="table table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th data-column-id="Id">Id</th>
                    <th data-column-id="DisplayImage">Hình ảnh</th>
                    <th data-column-id="Title">Tiêu đề</th>
                    <th data-column-id="commands" data-formatter="commands"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>